baseURL: "https://wchuqi.github.io/" # 首页地址
title: "Couqiner's Blog" # 首页标题
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45 # google analytics在国内无法访问，需要注释掉以加快访问速度

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Couqiner's Blog" # 首页标题
  description: "Lazy... no description" # 页面描述
  keywords: [Blog, Portfolio, PaperMod] # 首页的关键词
  author: Couqiner
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02 23:59:59" # 将时间格式修改为国内常用格式
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false # 在每篇文章开头显示目录
  tocopen: false

  # 各种图标的地址，如果没有就全部注释掉
  #assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    #favicon: "<link / abs url>"
    #favicon16x16: "<link / abs url>"
    #favicon32x32: "<link / abs url>"
    #apple_touch_icon: "<link / abs url>"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # PaperMod支持Regular、Home-Info和Profile三种模式，具体参阅 https://github.com/adityatelange/hugo-PaperMod/wiki/Features#regular-mode-default-mode
  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "Couqiner's Blog"
    subtitle: "oilllll"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  # 用于搜索引擎验证网站所有权，如果不用就注释掉
  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/wchuqi/wchuqi.github.io/blob/main/content" # 填入Github仓库的地址
    Text: "提交修改建议"
    appendFilePath: true # 是否在URL后加入文件路径

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archives # 需做额外配置，具体参考下文
      name: 归档
      url: /archives/
      weight: 10
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 20
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 30
    - identifier: search # 需做额外配置，具体参考下文
      name: 搜索
      url: /search/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
